apiVersion: apps/v1
kind: Deployment
metadata:
  name: autograder-deployment
  labels:
    app: autograder
spec:
  replicas: 2  # Nombre de r√©plicas pour le backend et le frontend
  selector:
    matchLabels:
      app: autograder
  template:
    metadata:
      labels:
        app: autograder
    spec:
      containers:
      - name: frontend
        image: hasindrae/autograder-frontend:latest
        ports:
        - containerPort: 80

      - name: backend
        image: hasindrae/autograder-backend:latest 
        ports:
        - containerPort: 8000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-db:27017/autograderDB